# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

########################################
# Builder
########################################
FROM golang:1.24-alpine AS builder
# Install git for module fetching
RUN apk add --no-cache git
WORKDIR /app

# Copy go files and download modules
COPY go.mod go.sum ./
RUN go mod download

# Copy rest of the source
COPY . .

# Build static binary
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o qweather-mcp main.go

########################################
# Runtime image
########################################
FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/qweather-mcp ./

# Default to stdio transport
ENTRYPOINT ["/app/qweather-mcp","-transport","stdio"]
