# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4

########################################################
# Build stage
########################################################
FROM golang:1.23-alpine AS builder
WORKDIR /src
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -mod=readonly -trimpath -ldflags="-s -w" -o /app/qweather-mcp-go ./main.go

########################################################
# Final stage
########################################################
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates --no-install-recommends && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/qweather-mcp-go ./qweather-mcp-go
RUN chmod +x qweather-mcp-go
ENTRYPOINT ["/app/qweather-mcp-go"]
